### PR TITLE
fix more crashes with type params

### LINKED ISSUE #71: panic analysing generic function with struct param with generic field types
Latest commit (dc49ffed) is failing on our usage with Go 1.19.4.
Previous commit (cac433cd) runs fine.

```patch
Subject: [PATCH] Change to test data which panics
---
Index: testdata/script/typeparams.txtar
===================================================================
diff --git a/testdata/script/typeparams.txtar b/testdata/script/typeparams.txtar
--- a/testdata/script/typeparams.txtar	(revision dc49ffedcfbc1b49598bb6670d37b92a7a9ad7d6)
+++ b/testdata/script/typeparams.txtar	(date 1671665772622)
@@ -53,6 +53,11 @@
 	return t2
 }
 
+func genericStructFunc[T1 any, T2 any](t Tuple[T1, T2]) T2 {
+	return t.right
+}
+
 // otherwise Tuple isn't reachable.
 var Sink interface{} = new(Tuple[int, string])
```

Test output from the above:
```
        > ! exec unparam .
        [stderr]
        panic: /usr/local/go/src/go/types/sizes.go:82: assertion failed
        
        goroutine 1 [running]:
        go/types.assert(0x60?)
        	/usr/local/go/src/go/types/errors.go:27 +0x5b
        go/types.(*StdSizes).Alignof(0xc000138220, {0x79b360?, 0xc0001da060})
        	/usr/local/go/src/go/types/sizes.go:82 +0x1b6
        go/types.(*StdSizes).Offsetsof(0x79b248?, {0xc00010db40, 0x2, 0xc000046c00?})
        	/usr/local/go/src/go/types/sizes.go:123 +0xdc
        go/types.(*StdSizes).Sizeof(0xc000138220, {0x79b248?, 0xc0001d80e0})
        	/usr/local/go/src/go/types/sizes.go:176 +0x285
        mvdan.cc/unparam/check.(*Checker).checkFunc(0xc000141040, 0xc00017cc00, 0xc0001443c0?)
        	/home/duncan/.local/src/github.com/mvdan/unparam/check/check.go:599 +0x99d
        mvdan.cc/unparam/check.(*Checker).Check(0xc000141040)
        	/home/duncan/.local/src/github.com/mvdan/unparam/check/check.go:377 +0x78b
        mvdan.cc/unparam/check.(*Checker).lines(0xc000141040, {0xc00011c010?, 0x4d460f?, 0xc00008da30?})
        	/home/duncan/.local/src/github.com/mvdan/unparam/check/check.go:107 +0x16a
        mvdan.cc/unparam/check.UnusedParams(0x0, 0x0, 0x0, {0xc00011c010, 0x1, 0x1})
        	/home/duncan/.local/src/github.com/mvdan/unparam/check/check.go:44 +0xe5
        mvdan.cc/unparam.main1()
        	/home/duncan/.local/src/github.com/mvdan/unparam/main.go:37 +0x151
```

### PR DESCRIPTION
**Pull request by mgabeler-lee-6rs**
fixes #71

### CODE REVIEW

**Comment by duncanharris** [comment]
As expected resolves my original panic

**Comment by mvdan** [comment]
Surely there's an easeier way to do this, but a quick skim of the go/types API didn't point me to it.

**Comment by mgabeler-lee-6rs** [comment]
> Surely there's an easeier way to do this, but a quick skim of the go/types API didn't point me to it.

Yeah, I thought this too. There's some `internal/` stuff but nothing importable :disappointed: 

> Could avoid type param check for non-generic funcs (most of them?)

Good call, added, plus some tests to make sure it works correctly

**Review by mvdan — APPROVED** [review]
Thanks again! Nice work.

**Pull request merged**
